name: Check Chadwick Ids

on:
  workflow_dispatch:  # manually triggered
  schedule:
    - cron: '15 13 * * *'  # every day at 13:15 UTC (Pacific morning)

permissions:
  contents: read
  issues: write

jobs:
  check_sfbb:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout crosswalk-data repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Clone prism-tools
        run: |
          git clone https://github.com/statsvine/prism-tools.git tools

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tools/requirements.txt || true

      - name: Run chadwick check script
        id: run-script
        run: |
          python tools/crosswalk/validate_chadwick_ids.py data/mlb/players.csv --issues chadwick_issues.md --ignores-file .validation/ignore_chadwick.yaml
          if [ -f chadwick_issues.md ]; then
            echo "issues_file_found=1" >> $GITHUB_ENV
          fi

      - name: Find the last open report issue
        if: env.issues_file_found == '1'
        id: last-issue
        uses: micalevisk/last-issue-action@v2
        with:
          state: open
          labels: |
            mlb
            source-chadwick
            roster-gap

      - name: Create/update GitHub Issue
        if: env.issues_file_found == '1'
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: "ðŸ“‹ Chadwick ID differences found"
          content-filepath: ./chadwick_issues.md
          issue-number: ${{ steps.last-issue.outputs.issue-number }}
          labels: mlb, source-chadwick, roster-gap